### ISSUE TITLE
Development plan

### ISSUE THREAD

**Issue by timstaley** [SKA-ScienceDataProcessor/FastImaging#1]
# Current:
- [x] Issue #15: Pipeline / utility executables 
- [x] PR #13 Review and merge setup scripts for Vagrant development VM.
- [x] Issue #12: C++/Python wrapping (PyBind11 or Boost::Python?)
- [x] Refactor of 'oversampling' parameter handling (blocked by https://github.com/SKA-ScienceDataProcessor/FastImaging-Python/issues/1)
- [x] Scripts and accompanying documentation explaining how run the 'reduce' script under profiling / benchmarking.
- [ ] Documented results (preferably, scripts to generate and plot results) on scaling behaviour (to be discussed with Anna)
------------------------------
# Old

- [x] Issue #2: Integrate [cnpy](https://github.com/rogersce/cnpy/) into build and perform basic functionality tests 
- [x] Issue #3: Basic 1D convolution functions (tophat, sinc, `exp*sinc`)
- [x] Issue #6 : 2-d kernel generation from convolution functions:
- [x] Issue #4: Exact convolutional gridder (i.e. recalculate function for each pixel, for each UV sample).
- [x] Issue #5: UV gridsize parameters / calculations
- [x] Issue: Interpolated convolutional gridder (convolution kernel is precalculated for grid at a variety of sub-pixel offsets).
- [x] Issue #9: FFT / simple imaging script
- [x] Prolate spheroidal convolution function.
- [x] Issue #7: Integrate lib-armadillo into the CMake build, via git-submodule.
- [ ] Windowing / function (AKA 'taper').
- [ ] Issue: Implement flexible gridder weighting
- [ ] UVW rotation & phase correction for phase-rotation (aka image-plane faceting).
